# Generated by Django 4.1.7 on 2023-04-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={'verbose_name': 'categoriasProd'},
        ),
    ]
